services:
  backend:
    build: ./backend
    volumes:
      - todo-data:/data
    expose:
      - "6001"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  todo-data:
