services:
  backend:
    build: ./backend
    volumes:
      - todo-data:/data
    expose:
      - "6001"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend

volumes:
  todo-data:
